### ISSUE TITLE
SCFormConfig null values

### ISSUE THREAD

**Issue by frankrowe** [boundlessgeo/spatialconnect-android-sdk#71]
The android SDK returns form configs with null values for fields that do not have a value set.

config from server
```javascript
{
  "key": "team",
  "type": "string",
  "is_required": false,
  "label": "Favorite?",
  "id": "a214590d-8673-420b-8bca-aa2877b45c52",
  "form_id": 2,
  "position": 0
}
```
config from sdk
```javascript
{
  "key": "team",
  "initial_value": "null",
  "type": "string",
  "order": 0,
  "is_required": false,
  "label": "Favorite?",
  "pattern": null,
  "is_integer": false,
  "id": "a214590d-8673-420b-8bca-aa2877b45c52"
}
```

Should these be removed from SCFormConfig, or be `null`?

**Comment by tetriscode** [comment]
Removed. There is really not any benefit to bind anything beyond the mandatory keys of the form data to a model in the SDK. It actually constrains us to match a json schema to an object in the SDK. The entire JSON object above can be stored in a single JSONNode and passed to those that need it (i.e. Geopackage creating tables)
